import React, { useEffect } from 'react'
import { useStore } from 'zustand'
import { shoppingStore } from '../../../../store'
import { formatDate, formatMoney } from '../../../../helpers';

export const ShoppingAdmin = () => {

  const { getShoppings, shoppings, getShoppingsDetails, shoppingsDetails } = useStore(shoppingStore);

  useEffect(() => {
    getShoppings();
    getShoppingsDetails();
  }, []);


  return (
    <div className='shopping'>
      <div className="shopping__cards">
        <div className="shopping__card">
          <div className="shopping__icon shopping__icon--blue">
            <p className="shopping__text">Total Profits Achieved</p>
          </div>
          <div className="shopping__description shopping__description--blue">
            <p className="shopping__text">{formatMoney(shoppingsDetails?.total ?? 0)} </p>
          </div>
        </div>
        <div className="shopping__card">
          <div className="shopping__icon shopping__icon--blue">
            <p className="shopping__text">Company Earnings</p>
          </div>
          <div className="shopping__description shopping__description--blue">
            <p className="shopping__text">{formatMoney(shoppingsDetails?.company ?? 0)} </p>
          </div>
        </div>
        <div className="shopping__card">
          <div className="shopping__icon shopping__icon--blue">
            <p className="shopping__text">Value Generated by Partners</p>
          </div>
          <div className="shopping__description shopping__description--blue">
            <p className="shopping__text">{formatMoney(shoppingsDetails?.branches ?? 0)}</p>
          </div>
        </div>
        <div className="shopping__card">
          <div className="shopping__icon shopping__icon--blue">
            <p className="shopping__text">Gateway Cost</p>
          </div>
          <div className="shopping__description shopping__description--blue">
            <p className="shopping__text">{formatMoney(shoppingsDetails?.payment_gateway ?? 0)}</p>
          </div>
        </div>
        <div className="shopping__card">
          <div className="shopping__icon shopping__icon--blue">
            <p className="shopping__text">Tax Cost</p>
          </div>
          <div className="shopping__description shopping__description--blue">
            <p className="shopping__text">{formatMoney(shoppingsDetails?.tax ?? 0)}</p>
          </div>
        </div>
      </div>

      <div className='shopping__table'>
        <div className="shopping__conatinerTable">
          <table className="shopping__table">
            <thead className="shopping__table--orange">
              <tr>
                <th>User</th>
                <th>Purchased Products</th>
                <th>Detail</th>
                <th>Distribution</th>
              </tr>
            </thead>
            <tbody>
              {shoppings && shoppings.length > 0 ?
                shoppings.map((shoping, index) => (
                  <tr key={index}>
                    <td>
                      <div className='shopping__control'>
                        <span className='shopping__text-title'>{shoping.user.names} {shoping.user.last_names}</span>
                        <p className='shopping__text-normal'>{formatDate(shoping.created_at)}</p>
                      </div>
                    </td>
                    <td>
                      <div className='shopping__control'>
                        {shoping.products.map((product, index) => (
                          <>
                            <ul key={index}>
                              <li className="shopping__row">
                                <span className='shopping__text-title'>Product:</span>
                                <p className='shopping__text-normal'>Revu Surprise (x{product.amount})</p>
                              </li>
                              <li className="shopping__row">
                                <span className='shopping__text-title'>Business:</span>
                                <p className='shopping__text-normal'>{product.revu_surprise.businesse?.name}</p>
                              </li>
                              <li className="shopping__row">
                                <span className='shopping__text-title'>Branch:</span>
                                <p className='shopping__text-normal'>{product.revu_surprise.businesse?.branches.find((branch) => branch.id === product.revu_surprise.branch)?.number}</p>
                              </li>
                              <li className="shopping__row">
                                <span className='shopping__text-title'>Unit value:</span>
                                <p className='shopping__text-normal'>{formatMoney(product.price)}</p>
                              </li>
                              <li className="shopping__row">
                                <span className='shopping__text-title'>Total paid:</span>
                                <p className='shopping__text-normal' style={{ fontWeight: 'bold' }}> {formatMoney(product.total)}</p>
                              </li>
                            </ul>
                            {index === shoping.products.length - 1 ?
                              ''
                              :
                              <hr style={{ border: '1px dashed gray' }} />
                            }
                          </>
                        ))
                        }

                      </div>
                    </td>
                    <td>
                      <div className='shopping__control'>
                        <div className="shopping__row">
                          <span className='shopping__text-title'>Subtotal:</span>
                          <p className='shopping__text-normal'>{formatMoney(shoping.detail.subtotal)}</p>
                        </div>
                        <div className="shopping__row">
                          <span className='shopping__text-title'>% Gateway:</span>
                          <p className='shopping__text-normal'>({shoping.detail.payment_gateway.percentage}%) {formatMoney(shoping.detail.payment_gateway.value)}</p>
                        </div>
                        <div className="shopping__row">
                          <span className='shopping__text-title'>% Taxes:</span>
                          <p className='shopping__text-normal'>({shoping.detail.tax.percentage}%) {formatMoney(shoping.detail.tax.value)}</p>
                        </div>
                        <div className="shopping__row">
                          <span className='shopping__text-title'>Total:</span>
                          <p className='shopping__text-normal'>{formatMoney(shoping.detail.total)}</p>
                        </div>
                      </div>
                    </td>
                    <td>
                      <div className='shopping__control'>

                        <div className="shopping__row">
                          <span className='shopping__text-title'>Company:</span>
                          <p className='shopping__text-normal'>({shoping.distribution.company.percentage}%) {formatMoney(shoping.distribution.company.value)}</p>
                        </div>
                        <div className="shopping__row">
                          <span className='shopping__text-title'>Partner:</span>
                          <p className='shopping__text-normal'>({shoping.distribution.businesse.percentage}%) {formatMoney(shoping.distribution.businesse.value)}</p>
                        </div>
                        <div className="shopping__row">
                          <span className='shopping__text-title'>Gateway:</span>
                          <p className='shopping__text-normal'>({shoping.distribution.payment_gateway.percentage}%) {formatMoney(shoping.distribution.payment_gateway.value)}</p>
                        </div>
                        <div className="shopping__row">
                          <span className='shopping__text-title'>Taxes:</span>
                          <p className='shopping__text-normal'>({shoping.distribution.tax.percentage}%) {formatMoney(shoping.distribution.tax.value)}</p>
                        </div>
                      </div>
                    </td>
                  </tr>
                ))
                :
                <>
                  <tr>
                    <td className="center" colSpan={4} style={{ display: 'table-cell', borderRadius: '0 0 2rem 2rem' }}>
                      There is no information.
                    </td>
                  </tr>
                </>
              }
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
